# Generated by Django 3.2.13 on 2022-07-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'acid_stack',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('basedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acid_task_1.basedocument')),
            ],
            options={
                'db_table': 'acid_document',
            },
            bases=('acid_task_1.basedocument',),
        ),
        migrations.CreateModel(
            name='FailedDocument',
            fields=[
                ('basedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acid_task_1.basedocument')),
            ],
            options={
                'db_table': 'acid_failed_document',
            },
            bases=('acid_task_1.basedocument',),
        ),
        migrations.AddField(
            model_name='basedocument',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acid_task_1.stack', verbose_name='Пачка'),
        ),
    ]
