# Generated by Django 3.2.13 on 2022-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acid_task_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Признак валидности'),
        ),
    ]
